/* Generated by scripts/make-logo.mjs. Do not edit by hand. */
export const WORDMARK_SVG = `<svg class="lq-wordmark-svg" viewBox="0 0 146 32" role="img" aria-label="Lacquer">
  <g class="lq-mark" transform="scale(.32)">
    <rect class="lq-mark-plate" x="2" y="2" width="96" height="96" rx="22"></rect>
    <path data-lq-layer="script-shadow" d="M53.8 61.8C57.3 50.5 61.5 39.2 67.4 30.6C73 22.3 80.3 20.2 82.2 24.9C84.1 29.6 76.2 43.3 55 57.9M55 56.7C44.2 60.4 33.4 58.8 32.7 53.2C32 47.6 39.6 40.4 50.5 37.5M54.7 58.8C50.2 72.7 44.6 81.3 37.2 83.1C29.6 85 23.7 79 25.2 72C26.8 64.9 34.2 65.4 41.8 72.7C52.6 83 65.1 87.2 77.3 85.8C88.4 84.5 91.6 78.6 87.2 72" fill="none" class="lq-mark-script-bronze" stroke-width="9" stroke-linecap="round" stroke-linejoin="round" transform="translate(-1.5 1.4)"/>
  <path data-lq-layer="script" d="M53.8 61.8C57.3 50.5 61.5 39.2 67.4 30.6C73 22.3 80.3 20.2 82.2 24.9C84.1 29.6 76.2 43.3 55 57.9M55 56.7C44.2 60.4 33.4 58.8 32.7 53.2C32 47.6 39.6 40.4 50.5 37.5M54.7 58.8C50.2 72.7 44.6 81.3 37.2 83.1C29.6 85 23.7 79 25.2 72C26.8 64.9 34.2 65.4 41.8 72.7C52.6 83 65.1 87.2 77.3 85.8C88.4 84.5 91.6 78.6 87.2 72" fill="none" class="lq-mark-script-champagne" stroke-width="7.2" stroke-linecap="round" stroke-linejoin="round"/>
  </g>
  <text class="lq-wordmark-text" x="38" y="21">acquer</text>
</svg>`;
